// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
    }
}
namespace __Blazor.Test.TestComponent
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateTreeNode_0<TItem>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TItem __arg0, int __seq1, global::Microsoft.AspNetCore.Components.RenderFragment __arg1)
        {
        __builder.OpenComponent<global::Test.TreeNode<TItem>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Test.TreeNode<TItem>.
#nullable restore
#line (1,11)-(1,15) "x:\dir\subdir\Test\TestComponent.cshtml"
Item

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, "ChildContent", __arg1);
        __builder.CloseComponent();
        }

        public static void CreateTreeNode_0_CaptureParameters<TItem>(TItem __arg0, out TItem __arg0_out)
        {
            __arg0_out = __arg0;
        }
        public static void CreateTreeNode_1<TItem>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TItem __arg0, int __seq1, global::Microsoft.AspNetCore.Components.RenderFragment __arg1)
        {
        __builder.OpenComponent<global::Test.TreeNode<TItem>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Test.TreeNode<TItem>.
#nullable restore
#line (2,15)-(2,19) "x:\dir\subdir\Test\TestComponent.cshtml"
Item

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, "ChildContent", __arg1);
        __builder.CloseComponent();
        }

        public static void CreateTreeNode_1_CaptureParameters<TItem>(TItem __arg0, out TItem __arg0_out)
        {
            __arg0_out = __arg0;
        }
        public static void CreateTreeNode_2<TItem>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, TItem __syntheticArg0, int __seq0, global::Microsoft.AspNetCore.Components.RenderFragment __arg0)
        {
        __builder.OpenComponent<global::Test.TreeNode<TItem>>(seq);
        __builder.AddComponentParameter(__seq0, "ChildContent", __arg0);
        __builder.CloseComponent();
        }

        public static void CreateTreeNode_2_CaptureParameters<TItem>(TItem __syntheticArg0, out TItem __syntheticArg0_out)
        {
            __syntheticArg0_out = __syntheticArg0;
        }
        public static void CreateTreeNode_3<TItem>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, TItem __syntheticArg0)
        {
        __builder.OpenComponent<global::Test.TreeNode<TItem>>(seq);
        __builder.CloseComponent();
        }

        public static void CreateTreeNode_3_CaptureParameters<TItem>(TItem __syntheticArg0, out TItem __syntheticArg0_out)
        {
            __syntheticArg0_out = __syntheticArg0;
        }
        public static void CreateTreeNode_4<TItem>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, TItem __syntheticArg0)
        {
        __builder.OpenComponent<global::Test.TreeNode<TItem>>(seq);
        __builder.CloseComponent();
        }

        public static void CreateTreeNode_4_CaptureParameters<TItem>(TItem __syntheticArg0, out TItem __syntheticArg0_out)
        {
            __syntheticArg0_out = __syntheticArg0;
        }
    }
}
#pragma warning restore 1591
