// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            {
                global::__Blazor.Test.TestComponent.TypeInference.CreateTreeNode_0_CaptureParameters(
#nullable restore
#line (1,18)-(1,30) "x:\dir\subdir\Test\TestComponent.cshtml"
DateTime.Now

#line default
#line hidden
#nullable disable
                , out var __typeInferenceArg_0___arg0);
                global::__Blazor.Test.TestComponent.TypeInference.CreateTreeNode_0(__builder, 0, 1, __typeInferenceArg_0___arg0, 2, (__builder2) => {
                    {
                        global::__Blazor.Test.TestComponent.TypeInference.CreateTreeNode_1_CaptureParameters(
#nullable restore
#line (2,22)-(2,59) "x:\dir\subdir\Test\TestComponent.cshtml"
System.Threading.Thread.CurrentThread

#line default
#line hidden
#nullable disable
                        , out var __typeInferenceArg_1___arg0);
                        global::__Blazor.Test.TestComponent.TypeInference.CreateTreeNode_1(__builder2, 3, 4, __typeInferenceArg_1___arg0, 5, (__builder3) => {
                            {
                                global::__Blazor.Test.TestComponent.TypeInference.CreateTreeNode_2_CaptureParameters(__typeInferenceArg_1___arg0, out var __typeInferenceArg_2___syntheticArg0);
                                global::__Blazor.Test.TestComponent.TypeInference.CreateTreeNode_2(__builder3, 6, __typeInferenceArg_2___syntheticArg0, 7, (__builder4) => {
                                    {
                                        global::__Blazor.Test.TestComponent.TypeInference.CreateTreeNode_3_CaptureParameters(__typeInferenceArg_1___arg0, out var __typeInferenceArg_3___syntheticArg0);
                                        global::__Blazor.Test.TestComponent.TypeInference.CreateTreeNode_3(__builder4, 8, __typeInferenceArg_3___syntheticArg0);
                                        __typeInferenceArg_3___syntheticArg0 = default;
                                    }
                                }
                                );
                                __typeInferenceArg_2___syntheticArg0 = default;
                            }
                        }
                        );
                        __typeInferenceArg_1___arg0 = default;
                    }
                    __builder2.AddMarkupContent(9, "\r\n    ");
                    {
                        global::__Blazor.Test.TestComponent.TypeInference.CreateTreeNode_4_CaptureParameters(__typeInferenceArg_0___arg0, out var __typeInferenceArg_1___syntheticArg0);
                        global::__Blazor.Test.TestComponent.TypeInference.CreateTreeNode_4(__builder2, 10, __typeInferenceArg_1___syntheticArg0);
                        __typeInferenceArg_1___syntheticArg0 = default;
                    }
                }
                );
                __typeInferenceArg_0___arg0 = default;
            }
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
