// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            {
                global::__Blazor.Test.TestComponent.TypeInference.CreateParent_0_CaptureParameters(
#nullable restore
#line (1,17)-(1,73) "x:\dir\subdir\Test\TestComponent.cshtml"
new System.Collections.Generic.Dictionary<int, string>()

#line default
#line hidden
#nullable disable
                , out var __typeInferenceArg_0___arg0, 
#nullable restore
#line (1,84)-(1,101) "x:\dir\subdir\Test\TestComponent.cshtml"
DateTime.MinValue

#line default
#line hidden
#nullable disable
                , out var __typeInferenceArg_0___arg1);
                global::__Blazor.Test.TestComponent.TypeInference.CreateParent_0(__builder, 0, 1, __typeInferenceArg_0___arg0, 2, __typeInferenceArg_0___arg1, 3, (__builder2) => {
                    global::__Blazor.Test.TestComponent.TypeInference.CreateChild_1(__builder2, 4, __typeInferenceArg_0___arg1, __typeInferenceArg_0___arg0, __typeInferenceArg_0___arg0, 5, 
#nullable restore
#line (2,30)-(2,53) "x:\dir\subdir\Test\TestComponent.cshtml"
new[] { 'a', 'b', 'c' }

#line default
#line hidden
#nullable disable
                    );
                }
                );
                __typeInferenceArg_0___arg0 = default;
                __typeInferenceArg_0___arg1 = default;
            }
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
