// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            global::__Blazor.Test.TestComponent.TypeInference.CreateMyComponent_0(__builder, 0, 1, 
#nullable restore
#line (1,22)-(1,26) "x:\dir\subdir\Test\TestComponent.cshtml"
"hi"

#line default
#line hidden
#nullable disable
            );
            __builder.AddMarkupContent(2, "\r\n");
            global::__Blazor.Test.TestComponent.TypeInference.CreateMyComponent_1(__builder, 3, 4, 
#nullable restore
#line (2,22)-(2,36) "x:\dir\subdir\Test\TestComponent.cshtml"
"how are you?"

#line default
#line hidden
#nullable disable
            );
            __builder.AddMarkupContent(5, "\r\n");
            global::__Blazor.Test.TestComponent.TypeInference.CreateMyComponent_2(__builder, 6, 7, 
#nullable restore
#line (3,22)-(3,28) "x:\dir\subdir\Test\TestComponent.cshtml"
"bye!"

#line default
#line hidden
#nullable disable
            );
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
