// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            global::__Blazor.Test.TestComponent.TypeInference.CreateMyComponent_0(__builder, 0, 1, 
#nullable restore
#line (2,20)-(2,24) "x:\dir\subdir\Test\TestComponent.cshtml"
true

#line default
#line hidden
#nullable disable
            , 2, "str", 3, 
#nullable restore
#line (4,24)-(4,33) "x:\dir\subdir\Test\TestComponent.cshtml"
() => { }

#line default
#line hidden
#nullable disable
            , 4, 
#nullable restore
#line (5,22)-(5,23) "x:\dir\subdir\Test\TestComponent.cshtml"
c

#line default
#line hidden
#nullable disable
            , 5, 
#nullable restore
#line (1,33)-(1,34) "x:\dir\subdir\Test\TestComponent.cshtml"
c

#line default
#line hidden
#nullable disable
            , 6, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => c = __value, c)));
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
