// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            {
                global::__Blazor.Test.TestComponent.TypeInference.CreateParentOne_0_CaptureParameters(
#nullable restore
#line (1,20)-(1,32) "x:\dir\subdir\Test\TestComponent.cshtml"
int.MaxValue

#line default
#line hidden
#nullable disable
                , out var __typeInferenceArg_0___arg0);
                global::__Blazor.Test.TestComponent.TypeInference.CreateParentOne_0(__builder, 0, 1, __typeInferenceArg_0___arg0, 2, (__builder2) => {
                    {
                        global::__Blazor.Test.TestComponent.TypeInference.CreateParentTwo_1_CaptureParameters(
#nullable restore
#line (2,25)-(2,32) "x:\dir\subdir\Test\TestComponent.cshtml"
"Hello"

#line default
#line hidden
#nullable disable
                        , out var __typeInferenceArg_1___arg0);
                        global::__Blazor.Test.TestComponent.TypeInference.CreateParentTwo_1(__builder2, 3, 4, __typeInferenceArg_1___arg0, 5, (__builder3) => {
                            global::__Blazor.Test.TestComponent.TypeInference.CreateChild_2(__builder3, 6, __typeInferenceArg_0___arg0, __typeInferenceArg_1___arg0);
                        }
                        );
                        __typeInferenceArg_1___arg0 = default;
                    }
                }
                );
                __typeInferenceArg_0___arg0 = default;
            }
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
