// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
    }
}
namespace __Blazor.Test.TestComponent
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateParentOne_0<TOne>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TOne __arg0, int __seq1, global::Microsoft.AspNetCore.Components.RenderFragment __arg1)
        {
        __builder.OpenComponent<global::Test.ParentOne<TOne>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Test.ParentOne<TOne>.
#nullable restore
#line (1,12)-(1,17) "x:\dir\subdir\Test\TestComponent.cshtml"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, "ChildContent", __arg1);
        __builder.CloseComponent();
        }

        public static void CreateParentOne_0_CaptureParameters<TOne>(TOne __arg0, out TOne __arg0_out)
        {
            __arg0_out = __arg0;
        }
        public static void CreateParentTwo_1<TTwo>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TTwo __arg0, int __seq1, global::Microsoft.AspNetCore.Components.RenderFragment __arg1)
        {
        __builder.OpenComponent<global::Test.ParentTwo<TTwo>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Test.ParentTwo<TTwo>.
#nullable restore
#line (2,16)-(2,21) "x:\dir\subdir\Test\TestComponent.cshtml"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, "ChildContent", __arg1);
        __builder.CloseComponent();
        }

        public static void CreateParentTwo_1_CaptureParameters<TTwo>(TTwo __arg0, out TTwo __arg0_out)
        {
            __arg0_out = __arg0;
        }
        public static void CreateChild_2<TOne, TTwo>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, TOne __syntheticArg0, TTwo __syntheticArg1)
        {
        __builder.OpenComponent<global::Test.Child<TOne, TTwo>>(seq);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
