// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,12) "x:\dir\subdir\Test\UseTestComponent.cshtml"
using Test

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class UseTestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            global::__Blazor.Test.UseTestComponent.TypeInference.CreateTestComponent_0(__builder, 0, 1, 
#nullable restore
#line (2,23)-(2,29) "x:\dir\subdir\Test\UseTestComponent.cshtml"
items1

#line default
#line hidden
#nullable disable
            , 2, 
#nullable restore
#line (2,37)-(2,43) "x:\dir\subdir\Test\UseTestComponent.cshtml"
items2

#line default
#line hidden
#nullable disable
            , 3, 
#nullable restore
#line (2,51)-(2,57) "x:\dir\subdir\Test\UseTestComponent.cshtml"
items3

#line default
#line hidden
#nullable disable
            , 4, (context) => (__builder2) => {
                __builder2.OpenElement(5, "p");
#nullable restore
#line (3,9)-(3,31) 25 "x:\dir\subdir\Test\UseTestComponent.cshtml"
__builder2.AddContent(6, context[0].description

#line default
#line hidden
#nullable disable
                );
                __builder2.CloseElement();
            }
            );
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
