// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            global::__Blazor.Test.TestComponent.TypeInference.CreateMyComponent_0(__builder, 0, 1, 
#nullable restore
#line (1,20)-(1,36) "x:\dir\subdir\Test\TestComponent.cshtml"
new CustomType()

#line default
#line hidden
#nullable disable
            , 2, (context) => (__builder2) => {
#nullable restore
#line (1,39)-(1,57) 25 "x:\dir\subdir\Test\TestComponent.cshtml"
__builder2.AddContent(3, context.ToString()

#line default
#line hidden
#nullable disable
                );
            }
            );
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
